position = [0,0]
stop_text_color_index = 1 # 必填
stop_background_color_index = 1 # 必填
run_text_color_index = 3 # 必填
run_background_color_index = 2 # 必填

[[text_colors]]
# black
r = 0
g = 0
b = 0
a = 1

[[text_colors]]
# white
r = 1
g = 1
b = 1
a = 1

[[text_colors]]
# yellow
r = 0.8
g = 0.9
b = 0.6
a = 1

[[text_colors]]
# green
r = 0.2
g = 0.8
b = 0.2
a = 1

[[background_colors]]
# light
r = 0.9
g = 0.9
b = 0.9
a = 1

[[background_colors]]
# dark
r = 0.125
g = 0.134
b = 0.145
a = 1

[[background_colors]]
# transparent
r = 0
g = 0
b = 0
a = 0

[reminder]
text = ":) Time out!!!!!"
color = {r=1, g=1.0, b=0.0, a=0.8}
font_size = 180
 # 存在image_path时，将显示图片
image_path = "assets/reminder.gif"
width = 400
height = 400
